"""Type stubs for mc_worldgen"""

from typing import List, Optional

class Version:
    """Minecraft versions"""
    MC_B1_7: int = ...
    MC_B1_8: int = ...
    MC_1_0: int = ...
    MC_1_1: int = ...
    MC_1_2: int = ...
    MC_1_3: int = ...
    MC_1_4: int = ...
    MC_1_5: int = ...
    MC_1_6: int = ...
    MC_1_7: int = ...
    MC_1_8: int = ...
    MC_1_9: int = ...
    MC_1_10: int = ...
    MC_1_11: int = ...
    MC_1_12: int = ...
    MC_1_13: int = ...
    MC_1_14: int = ...
    MC_1_15: int = ...
    MC_1_16_1: int = ...
    MC_1_16: int = ...
    MC_1_17: int = ...
    MC_1_18: int = ...
    MC_1_19: int = ...
    MC_1_19_2: int = ...
    MC_1_19_4: int = ...
    MC_1_20: int = ...
    MC_1_21: int = ...
    MC_NEWEST: int = ...

class Dimension:
    """Minecraft dimensions"""
    NETHER: int = ...
    OVERWORLD: int = ...
    END: int = ...

class Flag:
    """Generator flags"""
    LARGE_BIOMES: int = ...
    NO_BETA_OCEAN: int = ...
    FORCE_OCEAN_VARIANTS: int = ...

class Biome:
    """Biome IDs"""
    ocean: int = ...
    plains: int = ...
    desert: int = ...
    mountains: int = ...
    extremeHills: int = ...
    forest: int = ...
    taiga: int = ...
    swamp: int = ...
    swampland: int = ...
    river: int = ...
    nether_wastes: int = ...
    hell: int = ...
    the_end: int = ...
    sky: int = ...
    frozen_ocean: int = ...
    frozenOcean: int = ...
    frozen_river: int = ...
    frozenRiver: int = ...
    snowy_tundra: int = ...
    icePlains: int = ...
    snowy_mountains: int = ...
    iceMountains: int = ...
    mushroom_fields: int = ...
    mushroomIsland: int = ...
    mushroom_field_shore: int = ...
    mushroomIslandShore: int = ...
    beach: int = ...
    desert_hills: int = ...
    desertHills: int = ...
    wooded_hills: int = ...
    forestHills: int = ...
    taiga_hills: int = ...
    taigaHills: int = ...
    mountain_edge: int = ...
    extremeHillsEdge: int = ...
    jungle: int = ...
    jungle_hills: int = ...
    jungleHills: int = ...
    jungle_edge: int = ...
    jungleEdge: int = ...
    deep_ocean: int = ...
    deepOcean: int = ...
    stone_shore: int = ...
    stoneBeach: int = ...
    snowy_beach: int = ...
    coldBeach: int = ...
    birch_forest: int = ...
    birchForest: int = ...
    birch_forest_hills: int = ...
    birchForestHills: int = ...
    dark_forest: int = ...
    roofedForest: int = ...
    snowy_taiga: int = ...
    coldTaiga: int = ...
    snowy_taiga_hills: int = ...
    coldTaigaHills: int = ...
    giant_tree_taiga: int = ...
    megaTaiga: int = ...
    giant_tree_taiga_hills: int = ...
    megaTaigaHills: int = ...
    wooded_mountains: int = ...
    extremeHillsPlus: int = ...
    savanna: int = ...
    savanna_plateau: int = ...
    savannaPlateau: int = ...
    badlands: int = ...
    mesa: int = ...
    wooded_badlands_plateau: int = ...
    mesaPlateau_F: int = ...
    badlands_plateau: int = ...
    mesaPlateau: int = ...
    small_end_islands: int = ...
    end_midlands: int = ...
    end_highlands: int = ...
    end_barrens: int = ...
    warm_ocean: int = ...
    warmOcean: int = ...
    lukewarm_ocean: int = ...
    lukewarmOcean: int = ...
    cold_ocean: int = ...
    coldOcean: int = ...
    deep_warm_ocean: int = ...
    warmDeepOcean: int = ...
    deep_lukewarm_ocean: int = ...
    lukewarmDeepOcean: int = ...
    deep_cold_ocean: int = ...
    coldDeepOcean: int = ...
    deep_frozen_ocean: int = ...
    frozenDeepOcean: int = ...
    seasonal_forest: int = ...
    rainforest: int = ...
    shrubland: int = ...
    the_void: int = ...
    sunflower_plains: int = ...
    desert_lakes: int = ...
    gravelly_mountains: int = ...
    flower_forest: int = ...
    taiga_mountains: int = ...
    swamp_hills: int = ...
    ice_spikes: int = ...
    modified_jungle: int = ...
    modified_jungle_edge: int = ...
    tall_birch_forest: int = ...
    tall_birch_hills: int = ...
    dark_forest_hills: int = ...
    snowy_taiga_mountains: int = ...
    giant_spruce_taiga: int = ...
    giant_spruce_taiga_hills: int = ...
    modified_gravelly_mountains: int = ...
    shattered_savanna: int = ...
    shattered_savanna_plateau: int = ...
    eroded_badlands: int = ...
    modified_wooded_badlands_plateau: int = ...
    modified_badlands_plateau: int = ...
    bamboo_jungle: int = ...
    bamboo_jungle_hills: int = ...
    soul_sand_valley: int = ...
    crimson_forest: int = ...
    warped_forest: int = ...
    basalt_deltas: int = ...
    dripstone_caves: int = ...
    lush_caves: int = ...
    meadow: int = ...
    grove: int = ...
    snowy_slopes: int = ...
    jagged_peaks: int = ...
    frozen_peaks: int = ...
    stony_peaks: int = ...
    old_growth_birch_forest: int = ...
    old_growth_pine_taiga: int = ...
    old_growth_spruce_taiga: int = ...
    snowy_plains: int = ...
    sparse_jungle: int = ...
    stony_shore: int = ...
    windswept_hills: int = ...
    windswept_forest: int = ...
    windswept_gravelly_hills: int = ...
    windswept_savanna: int = ...
    wooded_badlands: int = ...
    deep_dark: int = ...
    mangrove_swamp: int = ...
    cherry_grove: int = ...
    pale_garden: int = ...

class Generator:
    """Minecraft World Generator object."""

    def __init__(self, mc: int = ..., flags: int = ...) -> None:
        """
        Initialize the generator.

        Args:
            mc: Minecraft version (use Version constants).
            flags: Generator flags (use Flag constants).
        """
        ...

    def apply_seed(self, dim: int, seed: int) -> None:
        """
        Apply a world seed and dimension to the generator.

        Args:
            dim: The dimension (Dimension.OVERWORLD, Dimension.NETHER, Dimension.END).
            seed: The 64-bit integer world seed.
        """
        ...

    def get_biome_at(self, scale: int, x: int, y: int, z: int) -> int:
        """
        Get the biome ID at a specific coordinate and scale.

        Args:
            scale: The horizontal scale factor (1, 4, 16, 64, or 256).
            x: The X coordinate.
            y: The Y coordinate.
            z: The Z coordinate.

        Returns:
            The Biome ID.
        """
        ...

    def gen_biomes(self, scale: int, x: int, z: int, sx: int, sz: int, y: int = 0, sy: int = 1) -> List[int]:
        """
        Generate biomes for a given range.

        Args:
            scale: The horizontal scale factor (1, 4, 16, 64, or 256).
            x: The starting X coordinate.
            z: The starting Z coordinate.
            sx: The horizontal size in X direction.
            sz: The horizontal size in Z direction.
            y: The starting Y coordinate.
            sy: The vertical size.

        Returns:
            A flat list of biome IDs.
        """
        ...
